/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface EventTicketSummary {
    eventId: string;
    totalTicketsSold: bigint;
    eventTitle: string;
    totalRevenue: bigint;
}
export interface Event {
    id: string;
    status: EventStatus;
    title: string;
    ticketQuantity: bigint;
    city: string;
    createdAt: Time;
    description: string;
    organizerId: Principal;
    isFeatured: boolean;
    category: EventCategory;
    posterImage: ExternalBlob;
    ticketsRemaining: bigint;
    ticketPrice: bigint;
    location: string;
    datetime: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AdminAnalytics {
    totalTicketsSold: bigint;
    totalEvents: bigint;
    totalUsers: bigint;
}
export interface Ticket {
    eventId: string;
    paymentStatus: Variant_pending_confirmed;
    paymentMethod: PaymentMethod;
    userId: Principal;
    ticketId: string;
    bookingCode: string;
    timestamp: Time;
    quantity: bigint;
}
export interface UserProfile {
    displayName: string;
    role: UserRole;
    accountCreated: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum EventCategory {
    music = "music",
    community = "community",
    culture = "culture",
    festivals = "festivals",
    nightlife = "nightlife",
    comedy = "comedy",
    fashion = "fashion"
}
export enum EventStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum PaymentMethod {
    cash = "cash",
    wave = "wave",
    africellMoney = "africellMoney",
    qMoney = "qMoney"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_confirmed {
    pending = "pending",
    confirmed = "confirmed"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Approve an event. Admin only.
     */
    approveEvent(eventId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Book tickets for an event. Authenticated users only.
     */
    bookTickets(eventId: string, quantity: bigint, paymentMethod: PaymentMethod): Promise<Ticket>;
    /**
     * / Create a new event. Only authenticated users (organizers) may create events.
     */
    createEvent(title: string, description: string, category: EventCategory, city: string, datetime: Time, location: string, ticketPrice: bigint, ticketQuantity: bigint, posterImage: ExternalBlob): Promise<string>;
    /**
     * / Get basic analytics. Admin only.
     */
    getAdminAnalytics(): Promise<AdminAnalytics>;
    /**
     * / Get the caller's own user profile.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get a single event by ID. Public.
     */
    getEvent(eventId: string): Promise<Event | null>;
    /**
     * / List events created by the caller (organizer dashboard). Authenticated users only.
     */
    getMyEvents(): Promise<Array<Event>>;
    /**
     * / Get the caller's own tickets. Authenticated users only.
     */
    getMyTickets(): Promise<Array<Ticket>>;
    /**
     * / Get ticket sales summary per event. Admin only.
     */
    getTicketSalesSummary(): Promise<Array<EventTicketSummary>>;
    /**
     * / Get any user's profile. Callers may only view their own profile unless they are an admin.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Get tickets for a user. Users can only view their own tickets; admins can view any.
     */
    getUserTickets(user: Principal): Promise<Array<Ticket>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List all users with their profiles. Admin only.
     */
    listAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    /**
     * / List all approved events. Public.
     */
    listApprovedEvents(): Promise<Array<Event>>;
    /**
     * / List approved events by category. Public.
     */
    listEventsByCategory(category: EventCategory): Promise<Array<Event>>;
    /**
     * / List approved events by city. Public.
     */
    listEventsByCity(city: string): Promise<Array<Event>>;
    /**
     * / List all pending events. Admin only.
     */
    listPendingEvents(): Promise<Array<Event>>;
    /**
     * / Reject an event. Admin only.
     */
    rejectEvent(eventId: string): Promise<void>;
    /**
     * / Save / update the caller's own user profile.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Search approved events by title, description, or city. Public.
     */
    searchEvents(searchTerm: string): Promise<Array<Event>>;
    /**
     * / Set featured flag on an event. Admin only.
     */
    setEventFeatured(eventId: string, isFeatured: boolean): Promise<void>;
}
import type { Event as _Event, EventCategory as _EventCategory, EventStatus as _EventStatus, ExternalBlob as _ExternalBlob, PaymentMethod as _PaymentMethod, Ticket as _Ticket, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveEvent(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookTickets(arg0: string, arg1: bigint, arg2: PaymentMethod): Promise<Ticket> {
        if (this.processError) {
            try {
                const result = await this.actor.bookTickets(arg0, arg1, to_candid_PaymentMethod_n10(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Ticket_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookTickets(arg0, arg1, to_candid_PaymentMethod_n10(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Ticket_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: EventCategory, arg3: string, arg4: Time, arg5: string, arg6: bigint, arg7: bigint, arg8: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, to_candid_EventCategory_n17(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, to_candid_EventCategory_n17(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async getAdminAnalytics(): Promise<AdminAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAnalytics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEvents();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEvents();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTickets(): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTickets();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTickets();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketSalesSummary(): Promise<Array<EventTicketSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketSalesSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketSalesSummary();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTickets(arg0: Principal): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTickets(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTickets(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovedEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovedEvents();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovedEvents();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEventsByCategory(arg0: EventCategory): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEventsByCategory(to_candid_EventCategory_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEventsByCategory(to_candid_EventCategory_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEventsByCity(arg0: string): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEventsByCity(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEventsByCity(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingEvents();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingEvents();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectEvent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchEvents(arg0: string): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEvents(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEvents(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async setEventFeatured(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEventFeatured(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEventFeatured(arg0, arg1);
            return result;
        }
    }
}
function from_candid_EventCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventCategory): EventCategory {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Event_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Promise<Event> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PaymentMethod_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Promise<Event | null> {
    return value.length === 0 ? null : await from_candid_Event_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: string;
    paymentStatus: {
        pending: null;
    } | {
        confirmed: null;
    };
    paymentMethod: _PaymentMethod;
    userId: Principal;
    ticketId: string;
    bookingCode: string;
    timestamp: _Time;
    quantity: bigint;
}): {
    eventId: string;
    paymentStatus: Variant_pending_confirmed;
    paymentMethod: PaymentMethod;
    userId: Principal;
    ticketId: string;
    bookingCode: string;
    timestamp: Time;
    quantity: bigint;
} {
    return {
        eventId: value.eventId,
        paymentStatus: from_candid_variant_n14(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: from_candid_PaymentMethod_n15(_uploadFile, _downloadFile, value.paymentMethod),
        userId: value.userId,
        ticketId: value.ticketId,
        bookingCode: value.bookingCode,
        timestamp: value.timestamp,
        quantity: value.quantity
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    role: _UserRole;
    accountCreated: _Time;
}): {
    displayName: string;
    role: UserRole;
    accountCreated: Time;
} {
    return {
        displayName: value.displayName,
        role: from_candid_UserRole_n23(_uploadFile, _downloadFile, value.role),
        accountCreated: value.accountCreated
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _EventStatus;
    title: string;
    ticketQuantity: bigint;
    city: string;
    createdAt: _Time;
    description: string;
    organizerId: Principal;
    isFeatured: boolean;
    category: _EventCategory;
    posterImage: _ExternalBlob;
    ticketsRemaining: bigint;
    ticketPrice: bigint;
    location: string;
    datetime: _Time;
}): Promise<{
    id: string;
    status: EventStatus;
    title: string;
    ticketQuantity: bigint;
    city: string;
    createdAt: Time;
    description: string;
    organizerId: Principal;
    isFeatured: boolean;
    category: EventCategory;
    posterImage: ExternalBlob;
    ticketsRemaining: bigint;
    ticketPrice: bigint;
    location: string;
    datetime: Time;
}> {
    return {
        id: value.id,
        status: from_candid_EventStatus_n28(_uploadFile, _downloadFile, value.status),
        title: value.title,
        ticketQuantity: value.ticketQuantity,
        city: value.city,
        createdAt: value.createdAt,
        description: value.description,
        organizerId: value.organizerId,
        isFeatured: value.isFeatured,
        category: from_candid_EventCategory_n30(_uploadFile, _downloadFile, value.category),
        posterImage: await from_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.posterImage),
        ticketsRemaining: value.ticketsRemaining,
        ticketPrice: value.ticketPrice,
        location: value.location,
        datetime: value.datetime
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
}): Variant_pending_confirmed {
    return "pending" in value ? Variant_pending_confirmed.pending : "confirmed" in value ? Variant_pending_confirmed.confirmed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    wave: null;
} | {
    africellMoney: null;
} | {
    qMoney: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "wave" in value ? PaymentMethod.wave : "africellMoney" in value ? PaymentMethod.africellMoney : "qMoney" in value ? PaymentMethod.qMoney : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): EventStatus {
    return "pending" in value ? EventStatus.pending : "approved" in value ? EventStatus.approved : "rejected" in value ? EventStatus.rejected : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    music: null;
} | {
    community: null;
} | {
    culture: null;
} | {
    festivals: null;
} | {
    nightlife: null;
} | {
    comedy: null;
} | {
    fashion: null;
}): EventCategory {
    return "music" in value ? EventCategory.music : "community" in value ? EventCategory.community : "culture" in value ? EventCategory.culture : "festivals" in value ? EventCategory.festivals : "nightlife" in value ? EventCategory.nightlife : "comedy" in value ? EventCategory.comedy : "fashion" in value ? EventCategory.fashion : value;
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Promise<Array<Event>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Event_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n36(_uploadFile, _downloadFile, x));
}
function to_candid_EventCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): _EventCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PaymentMethod_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    role: UserRole;
    accountCreated: Time;
}): {
    displayName: string;
    role: _UserRole;
    accountCreated: _Time;
} {
    return {
        displayName: value.displayName,
        role: to_candid_UserRole_n8(_uploadFile, _downloadFile, value.role),
        accountCreated: value.accountCreated
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    wave: null;
} | {
    africellMoney: null;
} | {
    qMoney: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.wave ? {
        wave: null
    } : value == PaymentMethod.africellMoney ? {
        africellMoney: null
    } : value == PaymentMethod.qMoney ? {
        qMoney: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): {
    music: null;
} | {
    community: null;
} | {
    culture: null;
} | {
    festivals: null;
} | {
    nightlife: null;
} | {
    comedy: null;
} | {
    fashion: null;
} {
    return value == EventCategory.music ? {
        music: null
    } : value == EventCategory.community ? {
        community: null
    } : value == EventCategory.culture ? {
        culture: null
    } : value == EventCategory.festivals ? {
        festivals: null
    } : value == EventCategory.nightlife ? {
        nightlife: null
    } : value == EventCategory.comedy ? {
        comedy: null
    } : value == EventCategory.fashion ? {
        fashion: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
