/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'wave' : IDL.Null,
  'africellMoney' : IDL.Null,
  'qMoney' : IDL.Null,
});
export const Time = IDL.Int;
export const Ticket = IDL.Record({
  'eventId' : IDL.Text,
  'paymentStatus' : IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'ticketId' : IDL.Text,
  'bookingCode' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
});
export const EventCategory = IDL.Variant({
  'music' : IDL.Null,
  'community' : IDL.Null,
  'culture' : IDL.Null,
  'festivals' : IDL.Null,
  'nightlife' : IDL.Null,
  'comedy' : IDL.Null,
  'fashion' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdminAnalytics = IDL.Record({
  'totalTicketsSold' : IDL.Nat,
  'totalEvents' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'role' : UserRole,
  'accountCreated' : Time,
});
export const EventStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'status' : EventStatus,
  'title' : IDL.Text,
  'ticketQuantity' : IDL.Nat,
  'city' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'organizerId' : IDL.Principal,
  'isFeatured' : IDL.Bool,
  'category' : EventCategory,
  'posterImage' : ExternalBlob,
  'ticketsRemaining' : IDL.Nat,
  'ticketPrice' : IDL.Nat,
  'location' : IDL.Text,
  'datetime' : Time,
});
export const EventTicketSummary = IDL.Record({
  'eventId' : IDL.Text,
  'totalTicketsSold' : IDL.Nat,
  'eventTitle' : IDL.Text,
  'totalRevenue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveEvent' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookTickets' : IDL.Func([IDL.Text, IDL.Nat, PaymentMethod], [Ticket], []),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        EventCategory,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        ExternalBlob,
      ],
      [IDL.Text],
      [],
    ),
  'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getMyEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getMyTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getTicketSalesSummary' : IDL.Func(
      [],
      [IDL.Vec(EventTicketSummary)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTickets' : IDL.Func([IDL.Principal], [IDL.Vec(Ticket)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'listApprovedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listEventsByCategory' : IDL.Func(
      [EventCategory],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'listEventsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'listPendingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'rejectEvent' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'setEventFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'wave' : IDL.Null,
    'africellMoney' : IDL.Null,
    'qMoney' : IDL.Null,
  });
  const Time = IDL.Int;
  const Ticket = IDL.Record({
    'eventId' : IDL.Text,
    'paymentStatus' : IDL.Variant({
      'pending' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'ticketId' : IDL.Text,
    'bookingCode' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
  });
  const EventCategory = IDL.Variant({
    'music' : IDL.Null,
    'community' : IDL.Null,
    'culture' : IDL.Null,
    'festivals' : IDL.Null,
    'nightlife' : IDL.Null,
    'comedy' : IDL.Null,
    'fashion' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdminAnalytics = IDL.Record({
    'totalTicketsSold' : IDL.Nat,
    'totalEvents' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'role' : UserRole,
    'accountCreated' : Time,
  });
  const EventStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'status' : EventStatus,
    'title' : IDL.Text,
    'ticketQuantity' : IDL.Nat,
    'city' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'organizerId' : IDL.Principal,
    'isFeatured' : IDL.Bool,
    'category' : EventCategory,
    'posterImage' : ExternalBlob,
    'ticketsRemaining' : IDL.Nat,
    'ticketPrice' : IDL.Nat,
    'location' : IDL.Text,
    'datetime' : Time,
  });
  const EventTicketSummary = IDL.Record({
    'eventId' : IDL.Text,
    'totalTicketsSold' : IDL.Nat,
    'eventTitle' : IDL.Text,
    'totalRevenue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveEvent' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookTickets' : IDL.Func([IDL.Text, IDL.Nat, PaymentMethod], [Ticket], []),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          EventCategory,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          ExternalBlob,
        ],
        [IDL.Text],
        [],
      ),
    'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getMyEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getMyTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getTicketSalesSummary' : IDL.Func(
        [],
        [IDL.Vec(EventTicketSummary)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTickets' : IDL.Func([IDL.Principal], [IDL.Vec(Ticket)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'listApprovedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listEventsByCategory' : IDL.Func(
        [EventCategory],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'listEventsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'listPendingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'rejectEvent' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'setEventFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };