/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAnalytics {
  'totalTicketsSold' : bigint,
  'totalEvents' : bigint,
  'totalUsers' : bigint,
}
export interface Event {
  'id' : string,
  'status' : EventStatus,
  'title' : string,
  'ticketQuantity' : bigint,
  'city' : string,
  'createdAt' : Time,
  'description' : string,
  'organizerId' : Principal,
  'isFeatured' : boolean,
  'category' : EventCategory,
  'posterImage' : ExternalBlob,
  'ticketsRemaining' : bigint,
  'ticketPrice' : bigint,
  'location' : string,
  'datetime' : Time,
}
export type EventCategory = { 'music' : null } |
  { 'community' : null } |
  { 'culture' : null } |
  { 'festivals' : null } |
  { 'nightlife' : null } |
  { 'comedy' : null } |
  { 'fashion' : null };
export type EventStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface EventTicketSummary {
  'eventId' : string,
  'totalTicketsSold' : bigint,
  'eventTitle' : string,
  'totalRevenue' : bigint,
}
export type ExternalBlob = Uint8Array;
export type PaymentMethod = { 'cash' : null } |
  { 'wave' : null } |
  { 'africellMoney' : null } |
  { 'qMoney' : null };
export interface Ticket {
  'eventId' : string,
  'paymentStatus' : { 'pending' : null } |
    { 'confirmed' : null },
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'ticketId' : string,
  'bookingCode' : string,
  'timestamp' : Time,
  'quantity' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'role' : UserRole,
  'accountCreated' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Approve an event. Admin only.
   */
  'approveEvent' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Book tickets for an event. Authenticated users only.
   */
  'bookTickets' : ActorMethod<[string, bigint, PaymentMethod], Ticket>,
  /**
   * / Create a new event. Only authenticated users (organizers) may create events.
   */
  'createEvent' : ActorMethod<
    [
      string,
      string,
      EventCategory,
      string,
      Time,
      string,
      bigint,
      bigint,
      ExternalBlob,
    ],
    string
  >,
  /**
   * / Get basic analytics. Admin only.
   */
  'getAdminAnalytics' : ActorMethod<[], AdminAnalytics>,
  /**
   * / Get the caller's own user profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a single event by ID. Public.
   */
  'getEvent' : ActorMethod<[string], [] | [Event]>,
  /**
   * / List events created by the caller (organizer dashboard). Authenticated users only.
   */
  'getMyEvents' : ActorMethod<[], Array<Event>>,
  /**
   * / Get the caller's own tickets. Authenticated users only.
   */
  'getMyTickets' : ActorMethod<[], Array<Ticket>>,
  /**
   * / Get ticket sales summary per event. Admin only.
   */
  'getTicketSalesSummary' : ActorMethod<[], Array<EventTicketSummary>>,
  /**
   * / Get any user's profile. Callers may only view their own profile unless they are an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Get tickets for a user. Users can only view their own tickets; admins can view any.
   */
  'getUserTickets' : ActorMethod<[Principal], Array<Ticket>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all users with their profiles. Admin only.
   */
  'listAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  /**
   * / List all approved events. Public.
   */
  'listApprovedEvents' : ActorMethod<[], Array<Event>>,
  /**
   * / List approved events by category. Public.
   */
  'listEventsByCategory' : ActorMethod<[EventCategory], Array<Event>>,
  /**
   * / List approved events by city. Public.
   */
  'listEventsByCity' : ActorMethod<[string], Array<Event>>,
  /**
   * / List all pending events. Admin only.
   */
  'listPendingEvents' : ActorMethod<[], Array<Event>>,
  /**
   * / Reject an event. Admin only.
   */
  'rejectEvent' : ActorMethod<[string], undefined>,
  /**
   * / Save / update the caller's own user profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Search approved events by title, description, or city. Public.
   */
  'searchEvents' : ActorMethod<[string], Array<Event>>,
  /**
   * / Set featured flag on an event. Admin only.
   */
  'setEventFeatured' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];